//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shopaccjx2.data.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Donhang
    {
        public int Ma_donhang { get; set; }
        public string Vatpham { get; set; }
        public Nullable<int> soluong { get; set; }
        public string Nhanvat { get; set; }
        public Nullable<decimal> Tongtien { get; set; }
        public Nullable<int> Id_taikhoan { get; set; }
    }
}
