//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shopaccjx2.data.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Lichsugiaodich
    {
        public int Ma_lichsugiaodich { get; set; }
        public string Noidunggiaodich { get; set; }
        public Nullable<int> Dongtien { get; set; }
        public Nullable<decimal> Sodubandau { get; set; }
        public Nullable<decimal> Sodusau { get; set; }
        public Nullable<int> Ma_taikhoan { get; set; }
    }
}
