//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shopaccjx2.data.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Loaitaikhoan
    {
        public int Ma_loaitaikhoan { get; set; }
        public string Loaitaikhoan1 { get; set; }
        public string Ghichu { get; set; }
    }
}
