//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shopaccjx2.data.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Nhanvat
    {
        public int Ma_nhanvat { get; set; }
        public string Kieuhinhnhanvat { get; set; }
        public Nullable<int> Capchuyensinh { get; set; }
        public string Huongchuyensinh { get; set; }
        public Nullable<int> Capdo { get; set; }
        public Nullable<decimal> Giaban { get; set; }
        public string Anhf3 { get; set; }
        public string Anhthongtin { get; set; }
        public string Anhchankhi { get; set; }
        public string Anhnon { get; set; }
        public string Anhao { get; set; }
        public string Anhquan { get; set; }
        public string Anhngoc { get; set; }
        public string Anhvukhi { get; set; }
        public string Anhtinvat { get; set; }
        public string Anhaochoang { get; set; }
        public string Anhhuychuong { get; set; }
        public string Anhgiay { get; set; }
        public string Anhmattich { get; set; }
        public string taikhoannv { get; set; }
        public string matkhaunv { get; set; }
        public string Ghichu { get; set; }
        public Nullable<bool> trangthai { get; set; }
        public Nullable<int> Ma_phai { get; set; }
        public Nullable<int> Ma_taikhoan { get; set; }
        public Nullable<System.DateTime> thoigiantao { get; set; }
    }
}
