//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shopaccjx2.data.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Phanhoi
    {
        public int Ma_phanhoi { get; set; }
        public string Noidungphanhoi { get; set; }
        public Nullable<int> Id_taikhoan { get; set; }
        public Nullable<bool> Trangthai { get; set; }
    }
}
