//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shopaccjx2.data.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class Shopaccjx2Entities : DbContext
    {
        public Shopaccjx2Entities()
            : base("name=Shopaccjx2Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Danhmuc> Danhmucs { get; set; }
        public virtual DbSet<Donhang> Donhangs { get; set; }
        public virtual DbSet<Lichsugiaodich> Lichsugiaodiches { get; set; }
        public virtual DbSet<Loaiphai> Loaiphais { get; set; }
        public virtual DbSet<Loaitaikhoan> Loaitaikhoans { get; set; }
        public virtual DbSet<Nganhang> Nganhangs { get; set; }
        public virtual DbSet<Nhanvat> Nhanvats { get; set; }
        public virtual DbSet<Phanhoi> Phanhois { get; set; }
        public virtual DbSet<Sodutaikhoan> Sodutaikhoans { get; set; }
        public virtual DbSet<Taikhoan> Taikhoans { get; set; }
        public virtual DbSet<Taikhoannganhang> Taikhoannganhangs { get; set; }
        public virtual DbSet<Vatpham> Vatphams { get; set; }
        public virtual DbSet<Monphai> Monphais { get; set; }
    
        public virtual ObjectResult<Layallvp_Result> Layallvp()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Layallvp_Result>("Layallvp");
        }
    
        public virtual ObjectResult<Layvptheoid_Result> Layvptheoid(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Layvptheoid_Result>("Layvptheoid", idParameter);
        }
    
        public virtual ObjectResult<Layallvpban_Result> Layallvpban()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Layallvpban_Result>("Layallvpban");
        }
    
        public virtual int Suavatpham(Nullable<int> ma_vatpham, string tenvatpham, Nullable<decimal> giaban, string mota, string anhvatpham, Nullable<bool> trangthai, Nullable<int> ma_danhmuc)
        {
            var ma_vatphamParameter = ma_vatpham.HasValue ?
                new ObjectParameter("Ma_vatpham", ma_vatpham) :
                new ObjectParameter("Ma_vatpham", typeof(int));
    
            var tenvatphamParameter = tenvatpham != null ?
                new ObjectParameter("Tenvatpham", tenvatpham) :
                new ObjectParameter("Tenvatpham", typeof(string));
    
            var giabanParameter = giaban.HasValue ?
                new ObjectParameter("Giaban", giaban) :
                new ObjectParameter("Giaban", typeof(decimal));
    
            var motaParameter = mota != null ?
                new ObjectParameter("Mota", mota) :
                new ObjectParameter("Mota", typeof(string));
    
            var anhvatphamParameter = anhvatpham != null ?
                new ObjectParameter("Anhvatpham", anhvatpham) :
                new ObjectParameter("Anhvatpham", typeof(string));
    
            var trangthaiParameter = trangthai.HasValue ?
                new ObjectParameter("Trangthai", trangthai) :
                new ObjectParameter("Trangthai", typeof(bool));
    
            var ma_danhmucParameter = ma_danhmuc.HasValue ?
                new ObjectParameter("Ma_danhmuc", ma_danhmuc) :
                new ObjectParameter("Ma_danhmuc", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Suavatpham", ma_vatphamParameter, tenvatphamParameter, giabanParameter, motaParameter, anhvatphamParameter, trangthaiParameter, ma_danhmucParameter);
        }
    
        public virtual int Themvatpham(string tenvatpham, Nullable<decimal> giaban, string mota, string anhvatpham, Nullable<bool> trangthai, Nullable<int> ma_danhmuc)
        {
            var tenvatphamParameter = tenvatpham != null ?
                new ObjectParameter("Tenvatpham", tenvatpham) :
                new ObjectParameter("Tenvatpham", typeof(string));
    
            var giabanParameter = giaban.HasValue ?
                new ObjectParameter("Giaban", giaban) :
                new ObjectParameter("Giaban", typeof(decimal));
    
            var motaParameter = mota != null ?
                new ObjectParameter("Mota", mota) :
                new ObjectParameter("Mota", typeof(string));
    
            var anhvatphamParameter = anhvatpham != null ?
                new ObjectParameter("Anhvatpham", anhvatpham) :
                new ObjectParameter("Anhvatpham", typeof(string));
    
            var trangthaiParameter = trangthai.HasValue ?
                new ObjectParameter("Trangthai", trangthai) :
                new ObjectParameter("Trangthai", typeof(bool));
    
            var ma_danhmucParameter = ma_danhmuc.HasValue ?
                new ObjectParameter("Ma_danhmuc", ma_danhmuc) :
                new ObjectParameter("Ma_danhmuc", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Themvatpham", tenvatphamParameter, giabanParameter, motaParameter, anhvatphamParameter, trangthaiParameter, ma_danhmucParameter);
        }
    
        public virtual int Xoavatpham(Nullable<int> ma_vatpham)
        {
            var ma_vatphamParameter = ma_vatpham.HasValue ?
                new ObjectParameter("Ma_vatpham", ma_vatpham) :
                new ObjectParameter("Ma_vatpham", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Xoavatpham", ma_vatphamParameter);
        }
    
        public virtual ObjectResult<Laytatcaloaiphai_Result> Laytatcaloaiphai()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Laytatcaloaiphai_Result>("Laytatcaloaiphai");
        }
    }
}
