//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shopaccjx2.data.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class Shopaccjx2Entities : DbContext
    {
        public Shopaccjx2Entities()
            : base("name=Shopaccjx2Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Danhmuc> Danhmucs { get; set; }
        public virtual DbSet<Donhang> Donhangs { get; set; }
        public virtual DbSet<Lichsugiaodich> Lichsugiaodiches { get; set; }
        public virtual DbSet<Loaiphai> Loaiphais { get; set; }
        public virtual DbSet<Loaitaikhoan> Loaitaikhoans { get; set; }
        public virtual DbSet<Nganhang> Nganhangs { get; set; }
        public virtual DbSet<Nhanvat> Nhanvats { get; set; }
        public virtual DbSet<Phanhoi> Phanhois { get; set; }
        public virtual DbSet<Sodutaikhoan> Sodutaikhoans { get; set; }
        public virtual DbSet<Taikhoan> Taikhoans { get; set; }
        public virtual DbSet<Taikhoannganhang> Taikhoannganhangs { get; set; }
        public virtual DbSet<Vatpham> Vatphams { get; set; }
    
        public virtual ObjectResult<Layallvp_Result> Layallvp()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Layallvp_Result>("Layallvp");
        }
    
        public virtual ObjectResult<Layvptheoid_Result> Layvptheoid(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Layvptheoid_Result>("Layvptheoid", idParameter);
        }
    }
}
