//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shopaccjx2.data.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sodutaikhoan
    {
        public int Ma_sdtk { get; set; }
        public Nullable<int> Ma_taikhoan { get; set; }
        public Nullable<int> Sodutaikhoan1 { get; set; }
    }
}
