//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shopaccjx2.data.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Taikhoan
    {
        public int Ma_taikhoan { get; set; }
        public string Tentaikhoan { get; set; }
        public string Matkhau { get; set; }
        public string Maukhau2 { get; set; }
        public string Tennguoidung { get; set; }
        public Nullable<System.DateTime> ngaysinh { get; set; }
        public string Diachi { get; set; }
        public string Email { get; set; }
        public Nullable<decimal> Sodutaikhoan { get; set; }
        public Nullable<bool> Trangthai { get; set; }
        public Nullable<int> Ma_loaitaikhoan { get; set; }
    }
}
