//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shopaccjx2.data.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Taikhoannganhang
    {
        public int Ma_Taikhoannganhang { get; set; }
        public Nullable<int> Sotaikhoan { get; set; }
        public string Tenchutaikhoan { get; set; }
        public Nullable<int> Ma_Taikhoan { get; set; }
        public Nullable<int> Ma_nganhang { get; set; }
    }
}
