//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shopaccjx2.data.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vatpham
    {
        public int Ma_vatpham { get; set; }
        public string Tenvatpham { get; set; }
        public Nullable<decimal> Giaban { get; set; }
        public string Mota { get; set; }
        public string Anhvatpham { get; set; }
        public Nullable<bool> Trangthai { get; set; }
        public Nullable<int> Ma_danhmuc { get; set; }
    }
}
